# Generated by Django 5.2.7 on 2025-10-26 10:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='presentation',
            name='document_extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pptx', 'ppt'])]),
        ),
        migrations.AddField(
            model_name='presentation',
            name='document_key_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='presentation',
            name='generated_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='presentation',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recording',
            name='content_coverage_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='improvement_from_previous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='iteration_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recording',
            name='missed_key_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('first_recording', 'First Recording'), ('first_completion', 'First Completion'), ('perfectionist', 'Perfectionist (90+ score)'), ('five_recordings', '5 Recordings'), ('ten_recordings', '10 Recordings'), ('level_up', 'Level Up'), ('max_level', 'Max Level'), ('improvement_streak', 'Improvement Streak')], max_length=50)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='presentations.presentation')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('presentation', 'badge_type')},
            },
        ),
    ]
